### ISSUE TITLE
Test bot weird behavior

### ISSUE THREAD

**Issue by tomlogan501** [MarkNaeem/ros_controllers#2]
Hi,
Following our mails, here is my observation of the test bot, I just launched it without any change of the configuration.
I noticed on your youtube videos the good behavior for pivot turn.

![Peek 2021-11-03 10-42](https://user-images.githubusercontent.com/56969577/140040478-8b507197-00ae-4c9b-8890-2b2ecc65479b.gif)

**Comment by MarkNaeem** [comment]
Hello,

Thanks for noticing. Wheels positions in the configuration YAML file were misordered which led to this bug. Positions of wheels 1 and 4, I guess, in this test platform were swapped. Solved!
