### ISSUE TITLE
Intersection not close enough (Odometry Bug!)

### ISSUE THREAD

**Issue by rajsurya1012** [MarkNaeem/ros_controllers#5]
When I am trying to run the test package, I am getting this error as 'Intersections are too close enough to get an average,dropping!'.
Kindly tell me how to fix it.
Thanks
![swerve_error](https://user-images.githubusercontent.com/42248521/151567937-4ae9cb0f-30e5-4ebe-a6ee-48b176e32502.png)

**Comment by MarkNaeem** [comment]
Hello,
This is left there intentionally for future fixes. As I mentioned before, odometry isn't mature enough just yet. This ros controller, like any other controller, contains a control algorithm, which is stable and well-tested, and an odometry part that's not maturely developed yet.

I have a set of papers from researchers discussing this specific area. The current implementation isn't the best available, hence the warning.

 It won't stop you from moving the vehicle around; This error is related to odometry only.
 
 My schedule is now much busier than before. And with no one willing to contribute to this work, it remains as is indefinitely.
