### ISSUE TITLE
What are the meaning of "open", "close open", "close", "open close"?

### ISSUE THREAD

**Issue by bxc237** [MarkNaeem/ros_controllers#7]
Hi, I'm trying to figure out the cause of the steering joint limits problem that I mentioned in #6.  Could you explain more about the `types_dict_` and `complement()` in the interval? Thank you.

**Comment by MarkNaeem** [comment]
Hello and thanks for your interest in my work.

I'm sorry but this is not an "issue" and this is used to track actual bugs and issues in the work. Requests to understand something is definitely not an issue so I'll close it and if you need any help, you can contact me! thaanks
